obj-m := switch-hook.o
switch-hook-objs := hook.o

# obj-m += switch-hook.o
# switch-hook-objs := hook.o

# KDIR ?= /lib/modules/$(shell uname -r)/build
# # EXTRA_CFLAGS=-I$(PWD)/../include

# all:
# 	# make -C $(KDIR) M=$(PWD) $(INC) modules
# 	make -C $(KDIR) M=$(PWD) modules

# clean:
# 	make -C $(KDIR) M=$(PWD) clean